name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUPERFLUID_WEBPAGE }}
      run: |
        echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUPERFLUID_WEBPAGE }} | sed 's/./& /g'
